version: "2"
services:

  streamsetsimage:
    container_name: streamsets
    build: build
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
      nproc: 65535
    ports:
      - "18630:18630"
    stdin_open: true
    volumes:
      - sdcconfig:/streamsets/etc
      - sdcdata:/streamsets/data
      - sdclog:/streamsets/log
      - sdcresources:/streamsets/resources
    networks:
      - universe

volumes:
  sdcconfig:
    driver: local
  sdclog:
    driver: local
  sdcdata:
    driver: local
  sdcresources:
    driver: local

networks:
  universe:
    external:
      name: universe-network
