version: "2"
services:

  streamsets:
    container_name: streamsets
    build: build
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    ports:
      - "18630:18630"
    volumes:
      - sdcconfig:/streamsets/etc
      - sdcdata:/streamsets/data
      - sdclog:/streamsets/log
      - sdcresources:/streamsets/resources
      - privateconfigure:/privateconfigure

volumes:
  sdcconfig:
    driver: local
  sdclog:
    driver: local
  sdcdata:
    driver: local
  sdcresources:
    driver: local
  privateconfigure:
    driver: local
